# docker-composeのバージョン
version: "3"

# 2つのサービスを定義
services:
  # postgres
  db:
    # ベースイメージ
    image: postgres:latest

    # ローカルのデータをdockerのディレクトリに同期する(コンテナが消えるたびにデータが消えちゃう)
    # 開発を楽にするために実施
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # 環境変数の設定(パスワード)
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: proadmaps_development

  # rails
  web:
    # 指定のディレクトリのdockerファイルをベースとする
    build: .
    # railsのサーバを起動している
    # その際にポートは3000,IPアドレスのバインドは0.0.0.0
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # ローカルのファイルとdockerファイルを同期するように設定
    volumes:
      - ./src:/app
    # ポート
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    # 依存関係を記載。通常、mysqlのipアドレスを記載する必要があるが、これを書かけばOK
    depends_on:
      - db
    tty: true
    stdin_open: true
