source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"
gem "rails", "~> 7.0.4"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"

gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "bootsnap", require: false

gem "rack-cors" # corsの管理

gem "jwt" # Auth0の認証の中で、JsonWebTokenを利用してAccess Tokenの検証をする

gem "active_model_serializers" # jsonを成形するライブラリ

group :development, :test do
  gem "debug", platforms: %i[mri mingw x64_mingw]
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
  gem "rspec-rails"
  gem "bullet" # N+1問題のチェック
end

group :development do end
